---
kind: pipeline
type: docker
name: default

platform:
    os: linux
    arch: amd64

steps:
- name: upload
  image: plugins/s3
  settings:
    bucket: rvgate.nl
    region: eu-central-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: ./**/*
    target: /
    acl: public-read
    exclude:
      - .git/**/*

---
kind: secret
name: aws_access_key_id
data: Xwh27GnY0eN8C8lj/mxfmjps6KtAf8VFyHHRuS4yech4UF4SJe3I8CuR94sfdD+m

---
kind: secret
name: aws_secret_access_key
data: brLk157q7vyt99JvwUfSeU1uRUqwFLqWo/Z9sUjZEcwAeiZZhjn2VTuI9dPiG2qXYhSGt+PIgHRCBbLQFv0PCF3GPUg=
